import type { Metadata } from "next";
import { Inter } from "next/font/google";
import AuthSession from "./AuthSession";
import NavBar from "./component/navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type Props = {
  children: React.ReactNode;
};
export default function RootLayout({ children }: Props) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthSession>
          <NavBar />
          {children}
        </AuthSession>
      </body>
    </html>
  );
}
